=== DCsabezY/ILQ2OXWebXML/ILQ2OX_1007/kurzusfelvetel/ILQ2OX_kurzusfelvetel.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">

    <xs:element name="ILQ2OX_kurzusfelvetel">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="hallgato"/>
                <xs:element ref="kurzusok"/>
            </xs:sequence>
            <xs:attribute name="tanév" type="tanevTipus" use="required"/>
            <xs:attribute name="egyetem" type="egyetemTipus" use="required"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="hallgato" type="hallgatoTipus"/>

    <xs:element name="kurzusok">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="kurzus" type="kurzusTipus" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:complexType name="hallgatoTipus">
        <xs:sequence>
            <xs:element name="hnev" type="xs:string"/>
            <xs:element name="szulev" type="xs:date"/>
            <xs:element name="szak" type="szakTipus"/>
        </xs:sequence>
        <xs:attribute name="id" type="idTipus" use="required"/>
    </xs:complexType>

    <xs:complexType name="szakTipus">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="evf" type="xs:gYear" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="kurzusTipus">
        <xs:sequence>
            <xs:element name="kurzusnev" type="xs:string"/>
            <xs:element name="kredit" type="kreditTipus"/>
            <xs:element name="hely" type="xs:string"/>
            <xs:element name="idopont" type="xs:string"/>
            <xs:element name="oktato" type="xs:string"/>
        </xs:sequence>
        <xs:attribute name="id" type="idTipus" use="required"/>
        <xs:attribute name="jovahagyas" type="igenNemTipus" default="nem"/>
    </xs:complexType>

    <xs:simpleType name="tanevTipus">
        <xs:restriction base="xs:string">
            <xs:pattern value="[0-9]{4}/[0-9]{2} (I|II)\."/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="egyetemTipus">
        <xs:restriction base="xs:string">
            <xs:enumeration value="ME"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="idTipus">
        <xs:restriction base="xs:string">
            <xs:pattern value="[A-Z0-9]{6}[A-Z0-9\-]*"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="igenNemTipus">
        <xs:restriction base="xs:string">
            <xs:enumeration value="igen"/>
            <xs:enumeration value="nem"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="kreditTipus">
        <xs:restriction base="xs:nonNegativeInteger">
            <xs:maxInclusive value="30"/>
        </xs:restriction>
    </xs:simpleType>

</xs:schema>

=== DCsabezY/ILQ2OXWebXML/ILQ2OX_1007/kurzusfelvetel/ILQ2OX_kurzusfelvetel.xml
<?xml version="1.0" encoding="UTF-8"?>


<ILQ2OX_kurzusfelvetel tanév = "2026/27 I." egyetem ="ME" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ILQ2OX_kurzusfelvetel.xsd"> 
    <hallgato id="ILQ2OX">
        <hnev>Deák Csaba</hnev>
        <szulev>2004-11-15</szulev>
        <szak evf = "2024">Mérnökinformatikus</szak>
    </hallgato>
    
    <kurzusok>
        <kurzus id="GEIAL332-B">
            <kurzusnev>Webes Adatkezelő Környezetek</kurzusnev>
            <kredit>5</kredit>
            <hely>Inf/101</hely>
            <idopont>Szerda 12:00-13:30</idopont>
            <oktato>Dr. Bednarik László</oktato>
        </kurzus>
        <kurzus id="MEIOKMUSZAN1">
            <kurzusnev>Angol műszaki szaknyelv 1.</kurzusnev>
            <kredit>0</kredit>
            <hely>/A/1 201</hely>
            <idopont>Hétfő 12:00-13:30</idopont>
            <oktato>Nagyné Varga Orsolya</oktato>
        </kurzus>
        <kurzus id="GEVEE050-B2">
            <kurzusnev>Elektrotechnika-elektronika</kurzusnev>
            <kredit>5</kredit>
            <hely>/A/1 316</hely>
            <idopont>Csütörtök 12:00-13:30</idopont>
            <oktato>Szabó Norbert István</oktato>
        </kurzus>
        
        <kurzus id="GEIAK310-B2">
            <kurzusnev>Játék prototípusok</kurzusnev>
            <kredit>5</kredit>
            <hely>/Inf/10</hely>
            <idopont>Csütörtök 16:00-19:30</idopont>
            <oktato>Dr. Nehéz Károly Róbert</oktato>
        </kurzus>
        <kurzus id="GEIAK130-B2">
            <kurzusnev>Mesterséges intelligencia alapok</kurzusnev>
            <kredit>5</kredit>
            <hely>/A/1 mf</hely>
            <idopont>kedd 8:00-12:00</idopont>
            <oktato>Kunné Dr. Tamás Judit</oktato>
        </kurzus>
        <kurzus id="GEIAL335-B2">
            <kurzusnev>Mobil programozási alapok</kurzusnev>
            <kredit>5</kredit>
            <hely>/A/1 5</hely>
            <idopont>Hétfő 16:00-20:00</idopont>
            <oktato>Dr. Agárdi Anita</oktato>
        </kurzus>
        <kurzus id="GEIAL331-B2">
            <kurzusnev>Web technológiák 1.</kurzusnev>
            <kredit>5</kredit>
            <hely>/A/1 201</hely>
            <idopont>Hétfő 10:00-12:00</idopont>
            <oktato>Dr. Agárdi Anita</oktato>
        </kurzus>
        <kurzus id="GEIAL30A-B2">
            <kurzusnev>Windows rendszergazda</kurzusnev>
            <kredit>5</kredit>
            <hely>/Inf/103</hely>
            <idopont>Kedd 16:00-20:00</idopont>
            <oktato>Dr. Wagner György</oktato>
        </kurzus>
    </kurzusok>
</ILQ2OX_kurzusfelvetel>
