=== DCsabezY/ILQ2OXWebXML/ILQ2OX_1007/órarend/ILQ2OX_orarend2.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:element name="ILQ2OX_orarend">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Ora" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="targy" type="xs:string"/>
                            <xs:element name="idopont">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="nap">
                                            <xs:simpleType>
                                                <xs:restriction base="xs:string">
                                                    <xs:enumeration value="Hétfő"/>
                                                    <xs:enumeration value="kedd"/>
                                                    <xs:enumeration value="szerda"/>
                                                    <xs:enumeration value="csütörtök"/>
                                                    <xs:enumeration value="péntek"/>
                                                    <xs:enumeration value="szombat"/>
                                                    <xs:enumeration value="vasárnap"/>
                                                </xs:restriction>
                                            </xs:simpleType>
                                        </xs:element>
                                        <xs:element name="tol" type="oraTipus"/>
                                        <xs:element name="ig" type="oraTipus"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="helyszin" type="xs:string"/>
                            <xs:element name="oktato" type="xs:string"/>
                            <xs:element name="szak" type="xs:string"/>
                        </xs:sequence>

                        <xs:attribute name="id" use="required">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:pattern value="[0-9]{2}"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>

                        <xs:attribute name="típus" use="required">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:enumeration value="elmelet"/>
                                    <xs:enumeration value="gyakorlat"/>
                                    <xs:enumeration value="szeminarium"/>
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:attribute>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:simpleType name="oraTipus">
        <xs:restriction base="xs:string">
            <xs:pattern value="([0-9]|1[0-9]|2[0-3])\.[0-5][0-9]"/>
        </xs:restriction>
    </xs:simpleType>

</xs:schema>

=== DCsabezY/ILQ2OXWebXML/ILQ2OX_1007/órarend/ILQ2OX_orarend.xml
<?xml version="1.0" encoding="UTF-8"?>

<ILQ2OX_orarend xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ILQ2OX_orarend2.xsd">
    <Ora id="01" típus="elmelet">
        <targy>Elektronika és elektrotechnika</targy>
        <idopont>
            <nap>Hétfő</nap>
            <tol>8.00</tol>
            <ig>9.30</ig>
        </idopont>
        <helyszin>3-as előadó</helyszin>
        <oktato>Szabó Norbert István</oktato>
        <szak>Mérnökinformatikus</szak>
    </Ora>
    <Ora id="02" típus="elmelet">
        <targy>Web technológiák 1.</targy>
        <idopont>
            <nap>Hétfő</nap>
            <tol>10.00</tol>
            <ig>11.30</ig>
        </idopont>
        <helyszin>5-ös előadó</helyszin>
        <oktato>Dr. Agárdi Anita</oktato>
        <szak>Mérnökinformatikus</szak>
    </Ora>
    <Ora id="03" típus="szeminarium">
        <targy>Angol műszaki szaknyelv 1.</targy>
        <idopont>
            <nap>Hétfő</nap>
            <tol>12.00</tol>
            <ig>13.30</ig>
        </idopont>
        <helyszin>A1/314</helyszin>
        <oktato>Nagyné Varga Orsolya</oktato>
        <szak>Mérnökinformatikus</szak>
    </Ora>
    <Ora id="04" típus="gyakorlat">
        <targy>Web technológiák 1.</targy>
        <idopont>
            <nap>Hétfő</nap>
            <tol>14.00</tol>
            <ig>15.30</ig>
        </idopont>
        <helyszin>ln/101</helyszin>
        <oktato>Dr. Agárdi Anita</oktato>
        <szak>Mérnökinformatikus</szak>
    </Ora>
    <Ora id="05" típus="elmelet">
        <targy>Mobil Programozás</targy>
        <idopont>
            <nap>Hétfő</nap>
            <tol>16.00</tol>
            <ig>17.30</ig>
        </idopont>
        <helyszin>ln/101</helyszin>
        <oktato>Dr. Agárdi Anita</oktato>
        <szak>Mérnökinformatikus</szak>
    </Ora>
    <Ora id="06" típus="gyakorlat">
        <targy>Mobil Programozás</targy>
        <idopont>
            <nap>Hétfő</nap>
            <tol>18.00</tol>
            <ig>19.30</ig>
        </idopont>
        <helyszin>ln/101</helyszin>
        <oktato>Dr. Agárdi Anita</oktato>
        <szak>Mérnökinformatikus</szak>
    </Ora>
    <Ora id="07" típus="gyakorlat">
        <targy>Mesterséges intelligencia alapok</targy>
        <idopont>
            <nap>kedd</nap>
            <tol>8.00</tol>
            <ig>9.30</ig>
        </idopont>
        <helyszin>32es előadó</helyszin>
        <oktato>Kunné Dr. Tamás Judit</oktato>
        <szak>Mérnökinformatikus</szak>
    </Ora>
    <Ora id="08" típus="elmelet">
        <targy>Mesterséges intelligencia alapok</targy>
        <idopont>
            <nap>kedd</nap>
            <tol>10.00</tol>
            <ig>11.30</ig>
        </idopont>
        <helyszin>32es előadó</helyszin>
        <oktato>Kunné Dr. Tamás Judit</oktato>
        <szak>Mérnökinformatikus</szak>
    </Ora>
    <Ora id="09" típus="elmelet">
        <targy>Windows Rendszergazda</targy>
        <idopont>
            <nap>kedd</nap>
            <tol>16.00</tol>
            <ig>17.30</ig>
        </idopont>
        <helyszin>ln/103</helyszin>
        <oktato>Huszák Péter</oktato>
        <szak>Mérnökinformatikus</szak>
    </Ora>
    <Ora id="10" típus="gyakorlat">
        <targy>Mesterséges intelligencia alapok</targy>
        <idopont>
            <nap>kedd</nap>
            <tol>18.00</tol>
            <ig>19.30</ig>
        </idopont>
        <helyszin>ln/103</helyszin>
        <oktato>Huszák Péter</oktato>
        <szak>Mérnökinformatikus</szak>
    </Ora>
    <Ora id="11" típus="elmelet">
        <targy>Webes adatkezelő környezetek</targy>
        <idopont>
            <nap>szerda</nap>
            <tol>8.00</tol>
            <ig>9.30</ig>
        </idopont>
        <helyszin>ln/202</helyszin>
        <oktato>Prof. Dr. Kovács László</oktato>
        <szak>Mérnökinformatikus</szak>
    </Ora>
    <Ora id="12" típus="gyakorlat">
        <targy>Webes adatkezelő környezetek</targy>
        <idopont>
            <nap>kedd</nap>
            <tol>12.00</tol>
            <ig>13.30</ig>
        </idopont>
        <helyszin>ln/101</helyszin>
        <oktato>Dr. Bednarik László</oktato>
        <szak>Mérnökinformatikus</szak>
    </Ora>
    <Ora id="13" típus="gyakorlat">
        <targy>Elektronika és elektrotechnika</targy>
        <idopont>
            <nap>csütörtök</nap>
            <tol>12.00</tol>
            <ig>13.30</ig>
        </idopont>
        <helyszin>A1/320</helyszin>
        <oktato>Szabó Norbert István</oktato>
        <szak>Mérnökinformatikus</szak>
    </Ora>
    <Ora id="14" típus="elmelet">
        <targy>Játék Prototípus</targy>
        <idopont>
            <nap>csütörtök</nap>
            <tol>16.00</tol>
            <ig>17.30</ig>
        </idopont>
        <helyszin>ln/15</helyszin>
        <oktato>Kiss Áron</oktato>
        <szak>Mérnökinformatikus</szak>
    </Ora>
    <Ora id="15" típus="gyakorlat">
        <targy>Játék Prototípus</targy>
        <idopont>
            <nap>csütörtök</nap>
            <tol>18.00</tol>
            <ig>19.30</ig>
        </idopont>
        <helyszin>ln/15</helyszin>
        <oktato>Kiss Áron</oktato>
        <szak>Mérnökinformatikus</szak>
    </Ora>
    
</ILQ2OX_orarend>
